theme: jekyll-theme-minimal
title: WW
description: M.D., Ph.D. (nuclear medicine) | Hobbyist (physics)
show_downloads: false

header_pages:
  - index.md
  - cv.md
  - research.md
  # - diary.md

plugins:
  - jekyll-scholar

# jekyll-scholar 설정 (스타일 지정 등)
scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibliography_item
